-- Quiz Questions Seed
-- 125 perguntas em 5 categorias

CREATE TABLE IF NOT EXISTS quiz_questions (
  id SERIAL PRIMARY KEY,
  question TEXT NOT NULL,
  options JSONB NOT NULL,
  answer_index INTEGER NOT NULL,
  category TEXT NOT NULL
);

ALTER TABLE quiz_questions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'quiz_questions' AND policyname = 'Anyone can read questions') THEN
    CREATE POLICY "Anyone can read questions" ON quiz_questions FOR SELECT USING (true);
  END IF;
END $$;

-- Only insert if table is empty
INSERT INTO quiz_questions (question, options, answer_index, category)
SELECT * FROM (VALUES
  ('Qual e a capital do Brasil?', '["Sao Paulo","Brasilia","Rio de Janeiro","Salvador"]'::jsonb, 1, 'geografia'),
  ('Qual e o maior pais do mundo em area?', '["China","EUA","Russia","Canada"]'::jsonb, 2, 'geografia'),
  ('Qual e o rio mais longo do Brasil?', '["Amazonas","Sao Francisco","Parana","Tocantins"]'::jsonb, 0, 'geografia'),
  ('Quantos estados tem o Brasil?', '["24","25","26","27"]'::jsonb, 2, 'geografia'),
  ('Qual oceano banha a costa brasileira?', '["Pacifico","Indico","Atlantico","Artico"]'::jsonb, 2, 'geografia'),
  ('Qual e o maior deserto do mundo?', '["Gobi","Kalahari","Saara","Atacama"]'::jsonb, 2, 'geografia'),
  ('Em qual continente fica o Egito?', '["Asia","Africa","Europa","Oceania"]'::jsonb, 1, 'geografia'),
  ('Qual e o pico mais alto do Brasil?', '["Pico da Neblina","Pico da Bandeira","Monte Roraima","Pico do Cristal"]'::jsonb, 0, 'geografia'),
  ('Qual pais tem formato de bota?', '["Grecia","Portugal","Italia","Espanha"]'::jsonb, 2, 'geografia'),
  ('Qual e a capital da Argentina?', '["Santiago","Montevideu","Buenos Aires","Lima"]'::jsonb, 2, 'geografia'),
  ('Qual e o menor pais do mundo?', '["Monaco","Vaticano","San Marino","Liechtenstein"]'::jsonb, 1, 'geografia'),
  ('Qual e o maior lago da America do Sul?', '["Titicaca","Maracaibo","Guaiba","Patos"]'::jsonb, 0, 'geografia'),
  ('Em que estado brasileiro fica a cidade de Manaus?', '["Para","Amazonas","Roraima","Acre"]'::jsonb, 1, 'geografia'),
  ('Qual e a montanha mais alta do mundo?', '["K2","Kangchenjunga","Everest","Lhotse"]'::jsonb, 2, 'geografia'),
  ('Qual pais tem mais habitantes no mundo?', '["India","EUA","China","Indonesia"]'::jsonb, 0, 'geografia'),
  ('Qual e a capital do Japao?', '["Osaka","Toquio","Quioto","Hiroshima"]'::jsonb, 1, 'geografia'),
  ('Qual rio corta a cidade de Paris?', '["Tamisa","Reno","Sena","Danubio"]'::jsonb, 2, 'geografia'),
  ('Qual e o maior estado do Brasil em area?', '["Minas Gerais","Para","Amazonas","Mato Grosso"]'::jsonb, 2, 'geografia'),
  ('Qual e a capital de Portugal?', '["Porto","Lisboa","Coimbra","Faro"]'::jsonb, 1, 'geografia'),
  ('Em que continente fica a Australia?', '["Asia","Oceania","America","Europa"]'::jsonb, 1, 'geografia'),
  ('Qual e o rio mais longo do mundo?', '["Amazonas","Nilo","Mississipi","Yangtzé"]'::jsonb, 1, 'geografia'),
  ('Qual pais e conhecido como "terra do sol nascente"?', '["China","Coreia do Sul","Japao","Tailandia"]'::jsonb, 2, 'geografia'),
  ('Qual e a capital da Alemanha?', '["Munique","Berlim","Frankfurt","Hamburgo"]'::jsonb, 1, 'geografia'),
  ('Quantos continentes existem?', '["5","6","7","8"]'::jsonb, 2, 'geografia'),
  ('Qual e o maior arquipelago do mundo?', '["Filipinas","Japao","Indonesia","Maldivas"]'::jsonb, 2, 'geografia'),
  ('Em que ano o Brasil foi descoberto?', '["1492","1500","1510","1498"]'::jsonb, 1, 'historia'),
  ('Quem proclamou a independencia do Brasil?', '["Tiradentes","D. Pedro I","D. Pedro II","Getulio Vargas"]'::jsonb, 1, 'historia'),
  ('Em que ano a escravidao foi abolida no Brasil?', '["1822","1889","1888","1900"]'::jsonb, 2, 'historia'),
  ('Quem foi o primeiro presidente do Brasil?', '["Getulio Vargas","Deodoro da Fonseca","Floriano Peixoto","Prudente de Morais"]'::jsonb, 1, 'historia'),
  ('Em que ano comecou a Segunda Guerra Mundial?', '["1935","1939","1941","1937"]'::jsonb, 1, 'historia'),
  ('Qual civilizacao construiu as piramides de Gize?', '["Romana","Grega","Egipcia","Mesopotamica"]'::jsonb, 2, 'historia'),
  ('Quem pintou a Mona Lisa?', '["Michelangelo","Rafael","Leonardo da Vinci","Donatello"]'::jsonb, 2, 'historia'),
  ('Em que ano o homem pisou na Lua pela primeira vez?', '["1965","1969","1971","1967"]'::jsonb, 1, 'historia'),
  ('Qual era o nome da esposa de D. Pedro I?', '["Leopoldina","Isabel","Maria","Carlota"]'::jsonb, 0, 'historia'),
  ('Em que ano caiu o Muro de Berlim?', '["1985","1989","1991","1987"]'::jsonb, 1, 'historia'),
  ('Quem liderou a Revolucao Francesa?', '["Napoleao","O povo","Luis XVI","Robespierre"]'::jsonb, 3, 'historia'),
  ('Qual foi a primeira capital do Brasil?', '["Rio de Janeiro","Brasilia","Salvador","Recife"]'::jsonb, 2, 'historia'),
  ('Em que seculo aconteceu o Renascimento?', '["XIII","XIV-XVI","XVII","XVIII"]'::jsonb, 1, 'historia'),
  ('Quem descobriu a America?', '["Vasco da Gama","Cristovao Colombo","Pedro Cabral","Americo Vespucio"]'::jsonb, 1, 'historia'),
  ('Qual imperador romano incendiou Roma?', '["Julio Cesar","Augusto","Nero","Caligula"]'::jsonb, 2, 'historia'),
  ('Em que ano o Brasil se tornou republica?', '["1822","1888","1889","1891"]'::jsonb, 2, 'historia'),
  ('Quem foi Cleópatra?', '["Rainha da Grecia","Rainha do Egito","Imperatriz de Roma","Rainha da Persia"]'::jsonb, 1, 'historia'),
  ('Qual guerra durou de 1914 a 1918?', '["Guerra Fria","Guerra do Vietna","Primeira Guerra Mundial","Guerra dos Cem Anos"]'::jsonb, 2, 'historia'),
  ('Quem foi Tiradentes?', '["Padre","Militar e dentista","Medico","Advogado"]'::jsonb, 1, 'historia'),
  ('Em que ano Brasilia foi inaugurada?', '["1950","1955","1960","1964"]'::jsonb, 2, 'historia'),
  ('Qual povo inventou a democracia?', '["Romanos","Gregos","Egipcios","Persas"]'::jsonb, 1, 'historia'),
  ('Quem escreveu "Os Lusiadas"?', '["Machado de Assis","Camoes","Fernando Pessoa","Gil Vicente"]'::jsonb, 1, 'historia'),
  ('Em que ano terminou a Segunda Guerra Mundial?', '["1943","1944","1945","1946"]'::jsonb, 2, 'historia'),
  ('Qual era o sistema politico do Brasil antes de 1889?', '["Republica","Monarquia","Ditadura","Anarquia"]'::jsonb, 1, 'historia'),
  ('Quem foi o ultimo imperador do Brasil?', '["D. Pedro I","D. Pedro II","D. Joao VI","D. Jose"]'::jsonb, 1, 'historia'),
  ('Quem criou o Mickey Mouse?', '["Pixar","Walt Disney","Warner Bros","DreamWorks"]'::jsonb, 1, 'cultura'),
  ('Qual e o nome do bruxo mais famoso da literatura?', '["Gandalf","Harry Potter","Merlin","Dumbledore"]'::jsonb, 1, 'cultura'),
  ('Quem interpretou Jack Sparrow?', '["Brad Pitt","Johnny Depp","Orlando Bloom","Tom Cruise"]'::jsonb, 1, 'cultura'),
  ('Qual banda lançou o album "Abbey Road"?', '["Rolling Stones","Queen","Beatles","Pink Floyd"]'::jsonb, 2, 'cultura'),
  ('Qual super-heroi e conhecido como "Homem de Aco"?', '["Batman","Homem-Aranha","Superman","Thor"]'::jsonb, 2, 'cultura'),
  ('Qual filme ganhou 11 Oscars em 2004?', '["Gladiador","O Senhor dos Aneis: O Retorno do Rei","Titanic","Ben-Hur"]'::jsonb, 1, 'cultura'),
  ('Quem cantou "Thriller"?', '["Prince","Michael Jackson","Stevie Wonder","Whitney Houston"]'::jsonb, 1, 'cultura'),
  ('Qual e o nome do pai do Simba em "O Rei Leao"?', '["Scar","Rafiki","Mufasa","Zazu"]'::jsonb, 2, 'cultura'),
  ('Em que ano foi lancado o primeiro iPhone?', '["2005","2006","2007","2008"]'::jsonb, 2, 'cultura'),
  ('Qual e o nome do vilao principal de Star Wars?', '["Darth Maul","Darth Vader","Kylo Ren","Palpatine"]'::jsonb, 1, 'cultura'),
  ('Quem escreveu "Game of Thrones"?', '["J.R.R. Tolkien","George R.R. Martin","Stephen King","J.K. Rowling"]'::jsonb, 1, 'cultura'),
  ('Qual rede social e representada por um passaro azul?', '["Facebook","Instagram","Twitter/X","LinkedIn"]'::jsonb, 2, 'cultura'),
  ('Quem e a "Rainha do Pop"?', '["Beyonce","Lady Gaga","Madonna","Rihanna"]'::jsonb, 2, 'cultura'),
  ('Qual personagem diz "Eu sou Groot"?', '["Rocket","Groot","Drax","Star-Lord"]'::jsonb, 1, 'cultura'),
  ('Qual serie se passa em Hawkins, Indiana?', '["The Walking Dead","Stranger Things","Dark","Lost"]'::jsonb, 1, 'cultura'),
  ('Quem dirigiu "Pulp Fiction"?', '["Martin Scorsese","Steven Spielberg","Quentin Tarantino","Christopher Nolan"]'::jsonb, 2, 'cultura'),
  ('Qual e o jogo de video game mais vendido da historia?', '["GTA V","Minecraft","Tetris","Mario Bros"]'::jsonb, 1, 'cultura'),
  ('Qual cantor e conhecido como "Rei do Rock"?', '["Chuck Berry","Elvis Presley","Little Richard","Buddy Holly"]'::jsonb, 1, 'cultura'),
  ('Qual e o nome da princesa de "Frozen"?', '["Anna e Elsa","Aurora","Rapunzel","Bela"]'::jsonb, 0, 'cultura'),
  ('Em qual cidade se passa "Friends"?', '["Los Angeles","Chicago","Nova York","Boston"]'::jsonb, 2, 'cultura'),
  ('Quem e o detetive mais famoso da literatura?', '["Hercule Poirot","Sherlock Holmes","Miss Marple","Philip Marlowe"]'::jsonb, 1, 'cultura'),
  ('Qual e o nome do protagonista de "Breaking Bad"?', '["Jesse Pinkman","Walter White","Hank Schrader","Saul Goodman"]'::jsonb, 1, 'cultura'),
  ('Qual filme conta a historia do navio que afundou em 1912?', '["Poseidon","Titanic","A Vida e Bela","Pearl Harbor"]'::jsonb, 1, 'cultura'),
  ('Quem interpretou o Coringa no filme de 2019?', '["Heath Ledger","Jack Nicholson","Joaquin Phoenix","Jared Leto"]'::jsonb, 2, 'cultura'),
  ('Qual banda cantou "Bohemian Rhapsody"?', '["Led Zeppelin","Queen","The Who","AC/DC"]'::jsonb, 1, 'cultura'),
  ('Qual e o elemento quimico mais abundante no universo?', '["Oxigenio","Carbono","Hidrogenio","Helio"]'::jsonb, 2, 'ciencias'),
  ('Qual planeta e conhecido como "planeta vermelho"?', '["Venus","Jupiter","Marte","Saturno"]'::jsonb, 2, 'ciencias'),
  ('Quantos ossos tem o corpo humano adulto?', '["196","206","216","226"]'::jsonb, 1, 'ciencias'),
  ('Qual e a formula quimica da agua?', '["CO2","H2O","NaCl","O2"]'::jsonb, 1, 'ciencias'),
  ('Qual e o maior orgao do corpo humano?', '["Figado","Cerebro","Pele","Intestino"]'::jsonb, 2, 'ciencias'),
  ('Qual gas as plantas absorvem da atmosfera?', '["Oxigenio","Nitrogenio","Gas carbonico","Hidrogenio"]'::jsonb, 2, 'ciencias'),
  ('Qual e a velocidade da luz?', '["300 mil km/s","150 mil km/s","500 mil km/s","1 milhao km/s"]'::jsonb, 0, 'ciencias'),
  ('Quem formulou a teoria da relatividade?', '["Newton","Einstein","Hawking","Bohr"]'::jsonb, 1, 'ciencias'),
  ('Qual e o planeta mais proximo do Sol?', '["Venus","Terra","Mercurio","Marte"]'::jsonb, 2, 'ciencias'),
  ('O que e DNA?', '["Acido ribonucleico","Acido desoxirribonucleico","Uma proteina","Um lipidio"]'::jsonb, 1, 'ciencias'),
  ('Qual e o metal mais abundante na crosta terrestre?', '["Ferro","Aluminio","Cobre","Ouro"]'::jsonb, 1, 'ciencias'),
  ('Quantos planetas tem o sistema solar?', '["7","8","9","10"]'::jsonb, 1, 'ciencias'),
  ('Qual e a unidade de medida de forca?', '["Watt","Joule","Newton","Pascal"]'::jsonb, 2, 'ciencias'),
  ('Qual vitamina e produzida pela exposicao ao sol?', '["Vitamina A","Vitamina C","Vitamina D","Vitamina E"]'::jsonb, 2, 'ciencias'),
  ('Qual e o gas mais abundante na atmosfera terrestre?', '["Oxigenio","Nitrogenio","Gas carbonico","Argonio"]'::jsonb, 1, 'ciencias'),
  ('Qual cientista descobriu a penicilina?', '["Pasteur","Fleming","Koch","Jenner"]'::jsonb, 1, 'ciencias'),
  ('Qual e a estrela mais proxima da Terra?', '["Sirius","Alpha Centauri","Sol","Proxima Centauri"]'::jsonb, 2, 'ciencias'),
  ('Qual parte da celula contem o DNA?', '["Membrana","Citoplasma","Nucleo","Ribossomo"]'::jsonb, 2, 'ciencias'),
  ('O que mede um termometro?', '["Pressao","Umidade","Temperatura","Altitude"]'::jsonb, 2, 'ciencias'),
  ('Qual e o simbolo quimico do ouro?', '["Ag","Fe","Au","Cu"]'::jsonb, 2, 'ciencias'),
  ('Qual e o maior planeta do sistema solar?', '["Saturno","Jupiter","Urano","Netuno"]'::jsonb, 1, 'ciencias'),
  ('O que e fotossintese?', '["Producao de luz","Producao de alimento pelas plantas","Decomposicao","Respiracao celular"]'::jsonb, 1, 'ciencias'),
  ('Qual orgao e responsavel por filtrar o sangue?', '["Figado","Coracao","Rim","Pulmao"]'::jsonb, 2, 'ciencias'),
  ('Qual e o ponto de ebulicao da agua ao nivel do mar?', '["90 graus C","100 graus C","110 graus C","120 graus C"]'::jsonb, 1, 'ciencias'),
  ('Quem e considerado o pai da fisica moderna?', '["Galileu","Newton","Einstein","Copérnico"]'::jsonb, 2, 'ciencias'),
  ('Quantas Copas do Mundo o Brasil ganhou?', '["3","4","5","6"]'::jsonb, 2, 'esportes'),
  ('Qual esporte usa raquete e peteca?', '["Tenis","Badminton","Squash","Ping-pong"]'::jsonb, 1, 'esportes'),
  ('Quantos jogadores tem um time de futebol em campo?', '["9","10","11","12"]'::jsonb, 2, 'esportes'),
  ('Qual pais sediou a Copa do Mundo de 2014?', '["Russia","Africa do Sul","Brasil","Alemanha"]'::jsonb, 2, 'esportes'),
  ('Quem e considerado o maior jogador de basquete?', '["Kobe Bryant","LeBron James","Michael Jordan","Magic Johnson"]'::jsonb, 2, 'esportes'),
  ('Qual e o esporte mais popular do mundo?', '["Basquete","Cricket","Futebol","Tenis"]'::jsonb, 2, 'esportes'),
  ('Quantos sets sao necessarios para vencer no volei?', '["2","3","5","4"]'::jsonb, 1, 'esportes'),
  ('Qual nadador tem mais medalhas olimpicas?', '["Ian Thorpe","Michael Phelps","Ryan Lochte","Mark Spitz"]'::jsonb, 1, 'esportes'),
  ('Qual pais inventou o futebol moderno?', '["Brasil","Alemanha","Inglaterra","Italia"]'::jsonb, 2, 'esportes'),
  ('Qual esporte e praticado em Wimbledon?', '["Golf","Cricket","Tenis","Polo"]'::jsonb, 2, 'esportes'),
  ('Quantas rodadas tem um jogo de boxe profissional?', '["10","12","15","8"]'::jsonb, 1, 'esportes'),
  ('Qual corredor jamaicano e recordista dos 100m rasos?', '["Asafa Powell","Usain Bolt","Yohan Blake","Tyson Gay"]'::jsonb, 1, 'esportes'),
  ('Qual selecao ganhou a Copa do Mundo de 2022?', '["Franca","Brasil","Argentina","Croacia"]'::jsonb, 2, 'esportes'),
  ('Quantos pontos vale um touchdown no futebol americano?', '["3","5","6","7"]'::jsonb, 2, 'esportes'),
  ('Qual tenista tem mais Grand Slams masculinos?', '["Roger Federer","Rafael Nadal","Novak Djokovic","Pete Sampras"]'::jsonb, 2, 'esportes'),
  ('Qual e a duracao de um jogo de futebol?', '["80 minutos","90 minutos","100 minutos","120 minutos"]'::jsonb, 1, 'esportes'),
  ('Qual esporte usa taco e bola em um campo verde?', '["Cricket","Baseball","Golf","Polo"]'::jsonb, 2, 'esportes'),
  ('Em que cidade serao as Olimpiadas de 2028?', '["Paris","Los Angeles","Toquio","Brisbane"]'::jsonb, 1, 'esportes'),
  ('Qual jogador brasileiro e conhecido como "Rei do Futebol"?', '["Garrincha","Zico","Pele","Ronaldo"]'::jsonb, 2, 'esportes'),
  ('Qual esporte e jogado em piscina com gol?', '["Polo aquatico","Nado sincronizado","Saltos ornamentais","Surf"]'::jsonb, 0, 'esportes'),
  ('Quantos jogadores tem um time de basquete em quadra?', '["4","5","6","7"]'::jsonb, 1, 'esportes'),
  ('Qual clube de futebol e conhecido como "Mengao"?', '["Vasco","Fluminense","Flamengo","Botafogo"]'::jsonb, 2, 'esportes'),
  ('Qual piloto de F1 tem mais titulos mundiais?', '["Ayrton Senna","Michael Schumacher","Lewis Hamilton","Max Verstappen"]'::jsonb, 2, 'esportes'),
  ('Qual esporte utiliza luvas e um ringue?', '["Judo","Karate","Boxe","Luta livre"]'::jsonb, 2, 'esportes'),
  ('Qual pais ganhou mais medalhas olimpicas na historia?', '["China","Russia","EUA","Gra-Bretanha"]'::jsonb, 2, 'esportes')
) AS v(question, options, answer_index, category)
WHERE NOT EXISTS (SELECT 1 FROM quiz_questions LIMIT 1);
